import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, MapPin, Heart, ChevronDown, SlidersHorizontal, BedDouble, Bath, Maximize, ArrowUpRight, Menu, X, Check, Bell, Plus, Building2, MessageCircle, Users, BarChart3, ShieldCheck, LogOut, ChevronRight, Sparkles } from 'lucide-react';
import './styles.css';

const properties = [
  { id: 1, title: 'The Maji House', location: 'Karen, Nairobi', price: 185000, beds: 4, baths: 3, sqft: '2,400', type: 'House', tag: 'Featured', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85', blurb: 'A quiet, light-filled home with lush garden views and thoughtful modern details.' },
  { id: 2, title: 'Windsor Park', location: 'Kilimani, Nairobi', price: 72000, beds: 2, baths: 2, sqft: '1,120', type: 'Apartment', tag: 'New this week', image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85', blurb: 'A warm contemporary apartment close to cafés, co-working spaces and the city.' },
  { id: 3, title: 'Coral Cove', location: 'Nyali, Mombasa', price: 110000, beds: 3, baths: 2, sqft: '1,850', type: 'Apartment', tag: 'Sea view', image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85', blurb: 'Resort-like coastal living with breezy rooms and a generous shared pool.' },
  { id: 4, title: 'The Acacia Loft', location: 'Westlands, Nairobi', price: 95000, beds: 2, baths: 2, sqft: '1,300', type: 'Apartment', tag: 'Pet friendly', image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85', blurb: 'An airy loft with character, skyline views and everything on your doorstep.' },
  { id: 5, title: 'Riverside Terraces', location: 'Riverside, Nairobi', price: 145000, beds: 3, baths: 3, sqft: '1,980', type: 'Townhouse', tag: 'Gated community', image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=85', blurb: 'Secure, spacious and calm — with leafy walks and room to grow.' },
  { id: 6, title: 'Milimani Garden Flat', location: 'Milimani, Kisumu', price: 58000, beds: 2, baths: 1, sqft: '980', type: 'Apartment', tag: 'Best value', image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=85', blurb: 'A beautifully kept flat with garden access in a peaceful neighbourhood.' },
];

const pendingLandlords = [{name:'Amina Wanjiku', email:'amina@serenespaces.co.ke', city:'Nairobi', initials:'AW'}, {name:'Brian Otieno', email:'brian@coastalliving.co.ke', city:'Mombasa', initials:'BO'}];
const pendingListings = [{title:'Sunset Ridge Villa', location:'Runda, Nairobi', owner:'Miriam N.'}, {title:'Bamburi Breeze', location:'Bamburi, Mombasa', owner:'David K.'}];

const money = (n) => `KSh ${n.toLocaleString('en-KE')}`;

function App(){
  const [screen, setScreen] = useState('home');
  const [mobileOpen, setMobileOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [location, setLocation] = useState('All locations');
  const [maxPrice, setMaxPrice] = useState('Any price');
  const [beds, setBeds] = useState('Any beds');
  const [favorites, setFavorites] = useState([]);
  const [selected, setSelected] = useState(null);
  const [toast, setToast] = useState('');
  const [landlords, setLandlords] = useState(pendingLandlords);
  const [listings, setListings] = useState(pendingListings);
  const [inquiryOpen, setInquiryOpen] = useState(false);

  const filtered = useMemo(() => properties.filter(p => {
    const text = `${p.title} ${p.location} ${p.type}`.toLowerCase();
    const q = query.toLowerCase();
    return (!q || text.includes(q)) && (location === 'All locations' || p.location.includes(location)) && (maxPrice === 'Any price' || (maxPrice === 'Under 100K' ? p.price < 100000 : maxPrice === 'Under 150K' ? p.price < 150000 : p.price < 75000)) && (beds === 'Any beds' || p.beds >= Number(beds));
  }), [query, location, maxPrice, beds]);

  const notify = (msg) => { setToast(msg); setTimeout(() => setToast(''), 2600); };
  const toggleFavorite = (id) => setFavorites(v => v.includes(id) ? v.filter(x=>x!==id) : [...v,id]);
  const go = (s) => { setScreen(s); setMobileOpen(false); window.scrollTo({top:0, behavior:'smooth'}); };

  return <div className="app">
    <header className="topbar">
      <button className="brand" onClick={()=>go('home')}><span className="brandMark"><span></span><span></span><span></span></span><span>house<span className="brandAccent">hunt</span></span></button>
      <nav className={mobileOpen ? 'nav open' : 'nav'}><button className={screen==='home'?'active':''} onClick={()=>go('home')}>Explore homes</button><button onClick={()=>notify('Saved homes are coming to your profile.')}>Saved homes {favorites.length>0 && <em>{favorites.length}</em>}</button><button onClick={()=>notify('Our neighbourhood guides are launching soon.')}>Neighbourhoods</button></nav>
      <div className="headerActions"><button className="listLink" onClick={()=>notify('Listing a home is free during the MVP.')}>List your home <ArrowUpRight size={15}/></button><button className="login" onClick={()=>go('admin')}>Sign in</button><button className="menuBtn" onClick={()=>setMobileOpen(!mobileOpen)}>{mobileOpen?<X/>:<Menu/>}</button></div>
    </header>

    {screen==='home' && <>
      <section className="hero"><div className="heroCopy"><div className="eyebrow"><span className="eyebrowLine"></span>Better places, better living</div><h1>Find a place<br/><i>to call home.</i></h1><p>Thoughtfully curated homes across Kenya, from people who care about where you live.</p><div className="trust"><div className="avatars"><span>JM</span><span>AK</span><span>SO</span><span>+</span></div><span><b>2,400+</b> happy house hunters</span></div></div><div className="heroPhoto"><img src="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=85"/><div className="heroBadge"><Sparkles size={16}/><span><b>Designed for living</b><small>Homes you'll love coming back to</small></span></div></div></section>
      <section className="searchPanel"><div className="searchTabs"><button className="selected">Rent a home</button><button>Buy a home</button></div><div className="searchFields"><label><span>Where</span><div className="inputWrap"><MapPin size={17}/><select value={location} onChange={e=>setLocation(e.target.value)}><option>All locations</option><option>Nairobi</option><option>Mombasa</option><option>Kisumu</option></select><ChevronDown size={16}/></div></label><label><span>Monthly budget</span><div className="inputWrap"><span className="ksh">KSh</span><select value={maxPrice} onChange={e=>setMaxPrice(e.target.value)}><option>Any price</option><option>Under 75K</option><option>Under 100K</option><option>Under 150K</option></select><ChevronDown size={16}/></div></label><label><span>Bedrooms</span><div className="inputWrap"><BedDouble size={17}/><select value={beds} onChange={e=>setBeds(e.target.value)}><option>Any beds</option><option value="1">1+ bedroom</option><option value="2">2+ bedrooms</option><option value="3">3+ bedrooms</option></select><ChevronDown size={16}/></div></label><button className="searchBtn" onClick={()=>document.getElementById('homes').scrollIntoView({behavior:'smooth'})}><Search size={19}/> Find a home</button></div></section>
      <main id="homes" className="main"><div className="sectionIntro"><div><div className="eyebrow"><span className="eyebrowLine"></span>Curated for you</div><h2>Homes worth<br/><i>coming home to.</i></h2></div><div className="introRight"><p>From first apartments to forever homes, discover spaces that fit the way you live.</p><button className="textBtn" onClick={()=>notify('Showing all available homes')}>View all homes <ArrowUpRight size={16}/></button></div></div>
        <div className="toolbar"><div className="resultCount"><b>{filtered.length}</b> homes that match your search</div><div className="toolbarControls"><button onClick={()=>notify('More filters coming soon')}><SlidersHorizontal size={16}/> Filters</button><button className="sortBtn">Sort: <b>Our picks</b><ChevronDown size={15}/></button></div></div>
        <div className="propertyGrid">{filtered.map(p=><PropertyCard key={p.id} p={p} favorite={favorites.includes(p.id)} onFavorite={()=>toggleFavorite(p.id)} onOpen={()=>setSelected(p)}/>)}</div>
        {filtered.length===0 && <div className="empty"><Search size={28}/><h3>No homes found</h3><p>Try widening your search or choosing a different location.</p><button onClick={()=>{setQuery('');setLocation('All locations');setMaxPrice('Any price');setBeds('Any beds')}}>Clear filters</button></div>}
      </main>
      <section className="how"><div className="eyebrow"><span className="eyebrowLine"></span>A simpler way to move</div><h2>House hunting,<br/><i>made human.</i></h2><div className="steps"><div><span>01</span><h3>Discover</h3><p>Browse real homes in the neighbourhoods you love, with the details that matter.</p></div><div><span>02</span><h3>Connect</h3><p>Talk directly to trusted landlords and arrange a viewing on your terms.</p></div><div><span>03</span><h3>Move in</h3><p>Find your fit, sign with confidence, and start making your space yours.</p></div></div></section>
      <footer><div className="brand footerBrand"><span className="brandMark"><span></span><span></span><span></span></span><span>house<span className="brandAccent">hunt</span></span></div><span>Made for the way Kenya lives.</span><span>© 2026 House Hunt</span></footer>
    </>}

    {screen==='admin' && <Admin go={go} landlords={landlords} setLandlords={setLandlords} listings={listings} setListings={setListings} notify={notify}/>} 
    {selected && <PropertyModal p={selected} favorite={favorites.includes(selected.id)} onFavorite={()=>toggleFavorite(selected.id)} onClose={()=>setSelected(null)} onInquiry={()=>setInquiryOpen(true)}/>} 
    {inquiryOpen && <InquiryModal onClose={()=>setInquiryOpen(false)} notify={notify}/>} 
    {toast && <div className="toast"><Check size={17}/>{toast}</div>}
  </div>
}

function PropertyCard({p,favorite,onFavorite,onOpen}){ return <article className="propertyCard"><div className="cardImage" onClick={onOpen}><img src={p.image} alt={p.title}/><span className="tag">{p.tag}</span><button className={favorite?'heart liked':'heart'} onClick={e=>{e.stopPropagation();onFavorite()}}><Heart size={18} fill={favorite?'currentColor':'none'}/></button><button className="viewArrow" onClick={onOpen}><ArrowUpRight size={19}/></button></div><div className="cardBody" onClick={onOpen}><div className="cardTitle"><h3>{p.title}</h3><span>{p.type}</span></div><div className="location"><MapPin size={14}/>{p.location}</div><div className="specs"><span><BedDouble size={15}/>{p.beds} beds</span><span><Bath size={15}/>{p.baths} baths</span><span><Maximize size={14}/>{p.sqft} sqft</span></div><div className="price">{money(p.price)} <small>/ month</small></div></div></article> }

function PropertyModal({p,favorite,onFavorite,onClose,onInquiry}){ return <div className="modalBack"><div className="modal propertyModal"><button className="modalClose" onClick={onClose}><X/></button><img className="modalImg" src={p.image} alt=""/><div className="modalContent"><div className="modalTag">{p.tag}</div><h2>{p.title}</h2><div className="location"><MapPin size={15}/>{p.location}</div><p>{p.blurb}</p><div className="modalSpecs"><span><BedDouble size={17}/><b>{p.beds}</b> bedrooms</span><span><Bath size={17}/><b>{p.baths}</b> bathrooms</span><span><Maximize size={16}/><b>{p.sqft}</b> sqft</span></div><div className="modalBottom"><div className="price">{money(p.price)} <small>/ month</small></div><button className="primary" onClick={onInquiry}><MessageCircle size={17}/> Contact landlord</button><button className={favorite?'iconBtn liked':'iconBtn'} onClick={onFavorite}><Heart size={18} fill={favorite?'currentColor':'none'}/></button></div></div></div></div> }
function InquiryModal({onClose,notify}){ const [sent,setSent]=useState(false); return <div className="modalBack"><div className="modal inquiry"><button className="modalClose" onClick={onClose}><X/></button>{sent?<div className="sent"><div className="sentIcon"><Check/></div><h2>Message sent.</h2><p>The landlord will get back to you shortly. Good luck with the viewing!</p><button className="primary" onClick={onClose}>Done</button></div>:<><div className="eyebrow"><span className="eyebrowLine"></span>Start a conversation</div><h2>Ask about this home.</h2><p className="muted">Introduce yourself and tell the landlord what you'd like to know.</p><input placeholder="Your name"/><input placeholder="Email or phone number"/><textarea placeholder="Hi, I'm interested in viewing this home..."></textarea><button className="primary wide" onClick={()=>{setSent(true);notify('Your inquiry has been sent')}}>Send inquiry <ArrowUpRight size={16}/></button></>}</div></div> }

function Admin({go,landlords,setLandlords,listings,setListings,notify}){ const [tab,setTab]=useState('overview'); return <div className="adminPage"><aside className="sidebar"><button className="brand sideBrand" onClick={()=>go('home')}><span className="brandMark"><span></span><span></span><span></span></span><span>house<span className="brandAccent">hunt</span></span></button><div className="sideLabel">Workspace</div><button className={tab==='overview'?'sideActive':''} onClick={()=>setTab('overview')}><BarChart3 size={18}/> Overview</button><button className={tab==='landlords'?'sideActive':''} onClick={()=>setTab('landlords')}><Users size={18}/> Landlords <em>{landlords.length}</em></button><button className={tab==='listings'?'sideActive':''} onClick={()=>setTab('listings')}><Building2 size={18}/> Listings <em>{listings.length}</em></button><button onClick={()=>notify('Inbox is ready for client messages.')}><MessageCircle size={18}/> Inbox</button><div className="sideBottom"><button onClick={()=>notify('Settings are coming soon')}><SlidersHorizontal size={18}/> Settings</button><button onClick={()=>go('home')}><LogOut size={18}/> Exit dashboard</button></div></aside><main className="adminMain"><div className="adminTop"><div><div className="eyebrow"><span className="eyebrowLine"></span>Sunday, 13 September 2026</div><h1>Good morning, <i>Admin.</i></h1></div><div className="adminActions"><button className="bell" onClick={()=>notify('You have 4 updates')}><Bell size={19}/><i></i></button><div className="adminAvatar">AD</div></div></div>{tab==='overview'?<Overview setTab={setTab}/>:<Moderation tab={tab} landlords={landlords} setLandlords={setLandlords} listings={listings} setListings={setListings} notify={notify}/>}</main></div> }
function Overview({setTab}){return <><div className="statGrid"><div><span>Total homes</span><b>1,284</b><small className="up">↑ 12.4% <i>vs last month</i></small></div><div><span>Active landlords</span><b>438</b><small className="up">↑ 8.2% <i>vs last month</i></small></div><div><span>New inquiries</span><b>286</b><small className="up">↑ 18.7% <i>vs last month</i></small></div><div><span>Pending review</span><b>09</b><small className="neutral">Needs your attention</small></div></div><div className="dashboardGrid"><div className="panel chartPanel"><div className="panelHead"><div><h3>Listing activity</h3><p>New homes added over the last 30 days</p></div><select><option>Last 30 days</option></select></div><div className="chart"><div className="ylabels"><span>120</span><span>80</span><span>40</span><span>0</span></div><div className="bars">{[42,56,48,67,61,74,58,76,80,68,87,74,94,84,100,86,108,92,102,115].map((h,i)=><span key={i} style={{height:`${h}%`}} className={i===17?'hot':''}></span>)}</div></div><div className="xlabels"><span>Aug 14</span><span>Aug 21</span><span>Aug 28</span><span>Sep 04</span><span>Sep 13</span></div></div><div className="panel actionPanel"><div className="panelHead"><div><h3>Needs your attention</h3><p>Keep House Hunt moving</p></div><ShieldCheck size={22}/></div><button onClick={()=>setTab('landlords')}><span className="actionIcon amber"><Users size={17}/></span><span><b>Approve landlords</b><small>2 waiting for review</small></span><ChevronRight/></button><button onClick={()=>setTab('listings')}><span className="actionIcon blue"><Building2 size={17}/></span><span><b>Review listings</b><small>2 new submissions</small></span><ChevronRight/></button><button><span className="actionIcon green"><MessageCircle size={17}/></span><span><b>Reply to inquiries</b><small>5 conversations open</small></span><ChevronRight/></button></div></div></>}
function Moderation({tab,landlords,setLandlords,listings,setListings,notify}){ const isL=tab==='landlords'; return <div className="moderation"><div className="moderationHead"><div><div className="eyebrow"><span className="eyebrowLine"></span>Review queue</div><h2>{isL?'Landlord approvals':'Listing moderation'}</h2><p>{isL?'Review new landlord accounts before they can publish homes.':'Make sure every home meets our quality standards.'}</p></div><button className="filterBtn"><SlidersHorizontal size={16}/> Filters</button></div><div className="queueList">{isL?landlords.map((x,i)=><div className="queueItem" key={x.email}><div className="queueAvatar">{x.initials}</div><div className="queueInfo"><h3>{x.name}</h3><p>{x.email} · {x.city}</p><span>Submitted today</span></div><div className="queueActions"><button className="approve" onClick={()=>{setLandlords(landlords.filter((_,j)=>j!==i));notify(`${x.name} approved`)}}><Check size={15}/> Approve</button><button className="decline" onClick={()=>{setLandlords(landlords.filter((_,j)=>j!==i));notify('Application declined')}}>Decline</button></div></div>):listings.map((x,i)=><div className="queueItem" key={x.title}><div className="listingThumb"><Building2 size={20}/></div><div className="queueInfo"><h3>{x.title}</h3><p>{x.location} · Listed by {x.owner}</p><span>Submitted 2 hours ago</span></div><div className="queueActions"><button className="approve" onClick={()=>{setListings(listings.filter((_,j)=>j!==i));notify(`${x.title} approved`)}}><Check size={15}/> Approve</button><button className="decline" onClick={()=>{setListings(listings.filter((_,j)=>j!==i));notify('Listing declined')}}>Decline</button></div></div>)}</div>{((isL&&landlords.length===0)||(!isL&&listings.length===0))&&<div className="empty queueEmpty"><Check size={27}/><h3>All clear</h3><p>You've reviewed everything in this queue.</p></div>}</div>}

createRoot(document.getElementById('root')).render(<App/>);
